DB設計のREADME追加
KatsuhiroSaito/freemarket_sample_39i pull request #18
Opened 2019-03-17 23:11 UTC by hujiyuta

DB設計のREADME追加しました
コメントお願いします。

2019-03-19 03:47 UTC, KatsuhiroSaito commented on README.md
> +|nickname|text|null: false  add_index:true|
textは文字数が多い情報を扱うデータなので、mail_addressやpasswordといった文字数が少ないものはstring型でいいのではないでしょうか？他のテーブルでtext型を使っているカラムに関しても、本当に(string型ではなく）text型の方が適しているのかご確認お願いします！

参照
https://chinatz.hatenablog.com/entry/2018/07/20/210000

2019-03-19 03:57 UTC, KatsuhiroSaito commented on README.md
> +|mobile_number|integer|null: false  |
電話番号に関しては、integer型ではなく、string型の方がいいようです。
なぜなら、integer型だと0から始まる数字が扱えないからです。電話番号の場合は080~や090~など0から始まる数字を扱う必要がありますので、string型の方が良いと思うのですが、いかがでしょうか？

参照
https://teratail.com/questions/24463

2019-03-19 04:14 UTC, KatsuhiroSaito commented on README.md
> +## top_categoryテーブル
テーブルの名称についてなんですが、個人的には"large (もしくは"big"）_category"、"mid_category"、"small_category"の方が自然な英語のように思われるのですがいかがでしょうか？

2019-03-19 04:21 UTC, KatsuhiroSaito commented on README.md
> +- has_many :transactions,throgh: :buyers
"throgh"ではなく、"through"ですね！uが抜けちゃってます😆

2019-03-19 04:32 UTC, KatsuhiroSaito commented on README.md
> +## point_amountテーブル
Railsの規約によると、テーブル名は複数形にするそうです。

参照：https://diveintocode.jp/tips/naming

point_amountテーブルはpointsテーブルで良いと思うのですがいかがでしょうか？
他のテーブル名も複数形になっていないものがあれば、修正お願いいたします！

2019-03-19 04:38 UTC, KatsuhiroSaito commented on README.md
> +|product_name|text|null: false  |
"product_name"や"product_description"としなくても、"name"や"description"でいい気がするのですがいかがでしょうか？

実際にviewで呼び出す場合は、@product.nameのようにインスタンス変数（@productの部分）を使って呼び出すので、カラム名がnameだけであっても、何のnameかはわかると思います。
むしろ、product_nameだと@product.product_nameになってしまい冗長的に感じるのですがいかがでしょうか？

2019-03-19 12:51 UTC, hujiyuta commented on README.md
> +|nickname|text|null: false  add_index:true|
修正しました！
imageのファイル名はstringが一般的とのことでした。
https://teratail.com/questions/157221

2019-03-19 13:01 UTC, hujiyuta commented on README.md
> +|mobile_number|integer|null: false  |
string型に修正しました。
計算しない項目は文字型がセオリーらしいです！
https://teratail.com/questions/43809

2019-03-19 13:02 UTC, hujiyuta commented on README.md
> +## top_categoryテーブル
一旦このままでお願いします！

2019-03-19 13:04 UTC, hujiyuta commented on README.md
> +- has_many :transactions,throgh: :buyers
typoです！ありがとうございます
修正しました

2019-03-19 13:09 UTC, hujiyuta commented on README.md
> +## point_amountテーブル
修正しました！ER図では複数形で定義していましたが、READMEに書き換えるに失念してました！

2019-03-19 13:36 UTC, hujiyuta commented on README.md
> +|product_name|text|null: false  |
修正しました！
この点、自分もREADME書きながら冗長的だと思ってましたが、検討できてなかったです！
指摘通り、インスタンス変数.カラム名でいけると思います。
ネストしたモデルでもおそらく大丈夫そうです。

https://teratail.com/questions/8955
https://qiita.com/hikaruna/items/f9b3de69c25e88138192

2019-03-22 12:10 UTC, KatsuhiroSaito commented on README.md
> +## user_informationsテーブル
informationは不可算名詞なので、user_informationで大丈夫です。
もしくは、下のQittaに書いてあるように別の可算名詞に言い換えるかですね(例えば、user_details)。

参照：「モデルやメソッドに名前を付けるときは英語の品詞に気をつけよう: 名前を付けるときは可算名詞か不可算名詞かを意識する」https://qiita.com/jnchito/items/459d58ba652bf4763820

2019-03-22 12:31 UTC, KatsuhiroSaito commented on README.md
> +- personal_messageはフラグとして使用する。デフォルト設定を追加した。
personal_flagのことでしょうか？
ちなみに、「フラグとして使用する」というのはどういう意味でしょうか？

2019-03-22 12:43 UTC, KatsuhiroSaito commented on README.md
> +|packing_day_id|integer|null: false, foreign_key: true|
conditionsやdelivery_feesをproductsテーブルの1カラムとするのではなく、わざわざ別のテーブルに分けるのには何か理由があるのでしょうか？

2019-03-22 12:44 UTC, KatsuhiroSaito commented on README.md
> +|paking_day|string|null: false|
packing_dayですかね。

2019-03-22 12:45 UTC, KatsuhiroSaito commented on README.md
> +|mail_address|string|null: false  unique: true|
mail_addressだと住所を指すこともあるので、「email」でお願いします。

2019-03-22 12:46 UTC, KatsuhiroSaito commented on README.md
> +- has_many :payment_infomations
typo

payment_information

2019-03-22 13:00 UTC, KatsuhiroSaito commented on README.md
> +- transactioonテーブルで評価者、被評家者の管理をする
typo

transactionテーブル
被評価者

2019-03-22 13:07 UTC, KatsuhiroSaito commented on README.md
> +## point_amountsテーブル
テーブル名はpointsテーブルでいかがでしょうか？

2019-03-22 13:13 UTC, KatsuhiroSaito commented on README.md
> +## likesテーブル
このテーブルの役割がイマイチ、ピンと来ないのですが、
これはUsesテーブルとProductsテーブルの中間テーブルなのか、いいね機能（商品に対するいいねですか？出品者に対するいいねですか？）のテーブルなのかどっちでしょうか？

備考に書いてあることとテーブル名がマッチしておらず、混乱中です。

2019-03-22 13:15 UTC, KatsuhiroSaito commented on README.md
> +- trasactionテーブルは２つの中間テーブル（buyer,seller）を経由してuserテーブルと多対多の関係性が存在
typo

transactionsテーブル

2019-03-22 13:29 UTC, KatsuhiroSaito commented on README.md
user_informationテーブルとの間に、has_oneの関係が成り立つと思うのですが、いかがでしょうか？

2019-03-22 21:35 UTC, hujiyuta commented on README.md
> +- personal_messageはフラグとして使用する。デフォルト設定を追加した。
ニュース一覧を見ていたら全体に送っているメッセージと「個別メッセージ」ラベルが付いているものがあるため、フラグが必要かと考えて追加しています。備考の記載が間違っていたので修正しました。

https://gyazo.com/caaf07a5624dc8b311f2d53fbecc3f59

2019-03-22 21:49 UTC, hujiyuta commented on README.md
> +|packing_day_id|integer|null: false, foreign_key: true|
実際の出品画面を見ると「商品の状態」、「配送料の負担」、「配送までの日数」をプルダウン メニューから選択するようです。選択肢の専用テーブルを作成することで管理・実装もし易くなるそうです！

出品画面
https://gyazo.com/913efa3dced4a076b20370fb688d25b4

参考記事
https://qiita.com/HrsUed/items/56677d6c266d8a53ffa7

2019-03-22 21:50 UTC, hujiyuta commented on README.md
> +|paking_day|string|null: false|
typoです！指摘ありがとうございます

2019-03-22 21:51 UTC, hujiyuta commented on README.md
> +|mail_address|string|null: false  unique: true|
修正しました！

2019-03-22 22:11 UTC, hujiyuta commented on README.md
> +## user_informationsテーブル
ありがとうございます！可算名詞に修正しました

2019-03-22 22:13 UTC, hujiyuta commented on README.md
> +- has_many :payment_infomations
こちらはpayment_methods（可算名詞）に変更しました。

2019-03-22 22:15 UTC, hujiyuta commented on README.md
> +- transactioonテーブルで評価者、被評家者の管理をする
修正しました

2019-03-22 22:17 UTC, hujiyuta commented on README.md
> +## point_amountsテーブル
修正しました

2019-03-22 22:58 UTC, hujiyuta commented on README.md
> +## likesテーブル
自分も理解が浅く、うまく内容を説明できないですが、備考内容を少し加筆しました。
like機能の実装にはこちらの記事が参考になるかと思います。
https://qiita.com/mohira/items/148c0f6ef89e8f62df72

2019-03-22 23:01 UTC, hujiyuta commented on README.md
> +- trasactionテーブルは２つの中間テーブル（buyer,seller）を経由してuserテーブルと多対多の関係性が存在
修正しました

2019-03-22 23:48 UTC, hujiyuta commented on README.md
こちらもlikesテーブルと同じ考え方で、usersテーブルとnewsfeedsテーブルには多対多の関係が成り立つと思われるため、中間テーブルとして「user_notifications」を作成しています。

以下の記事はあまり参考になりませんが、
お知らせ機能について同じような作り方（中間モデル：MsgToUserを作成）をしているようです。

https://teratail.com/questions/14824

2019-03-23 01:33 UTC, KatsuhiroSaito commented on README.md
紛らわしい書き方をして申し訳ありません。
私が言いたかったのは、usersテーブルとuser_detailsテーブル（旧：user_informationテーブル）間のアソシエーションです。

user_detail belongs_to user であり、
user has_one user_detailではないでしょうか？

2019-03-23 22:18 UTC, hujiyuta commented on README.md
ありがとうございます指摘の通りだと思います！修正しました

2019-03-31 08:37 UTC, hujiyuta commented
ER図も添付します。
https://gyazo.com/8129f7aedf6c818f10ff971733967c5e

2019-03-31 08:56 UTC, ghost requested changes

2019-03-31 08:56 UTC, hiroki5123 commented on README.md
> +## prefecturesテーブル
都道府県はactive＿hashで実装して欲しいです。
ですので、こちらのテーブルは作らないでください。

2019-03-31 12:11 UTC, hujiyuta commented on README.md
> +## prefecturesテーブル
コメント通り削除しました。

2019-03-31 12:23 UTC, kuroko918 reviewed
integer型だとforeign_keyによる外部キー制約が効かないので外部キーカラムは全てreferences型に変えましょう！

2019-03-31 12:23 UTC, kuroko918 commented on README.md
> +## top_categoriesテーブル
https://qiita.com/chopin3/items/ca5525406ef005086e59
こちらの記事を参考に、多階層テーブルとして、3つのcategoryをまとめて定義して下さい！

2019-04-01 22:52 UTC, hujiyuta commented on README.md
> +## top_categoriesテーブル
外部キーカラムは全てreferences型に変更
categoryは１つのテーブルにまとめました。

2019-04-02 00:21 UTC, miyagit commented on README.md
場合にもよりますが基本的にdependent: :destroyあったほうが良いと思います！
どこのテーブルが必要か考えて追記してもらえればと思います。

2019-04-02 22:32 UTC, hujiyuta commented on README.md
dependent: :destroyの関係性を追記しました

2019-04-03 02:06 UTC, TOMARUMARU approved these changes
LGTM

2019-04-03 02:43 UTC, KatsuhiroSaito commented on README.md
> +- has_one :user_detail, dependent: :destroy, class_name: UserDetail
typo
"user_detail" → "user_details"

2019-04-03 03:10 UTC, merged