【マークアップ】ユーザー新規登録/ログインページ ②
KatsuhiroSaito/freemarket_sample_39i pull request #22
Opened 2019-03-30 01:31 UTC by hujiyuta

ログイン画面と新規登録画面の作成

2019-04-07 08:46 UTC, hujiyuta commented
・BEMを意識して新規登録画面とログイン画面を作成
・ブロック毎にパーシャルファイルに分割

https://gyazo.com/210462dc3b7c8bcad792c42c51b5f568
https://gyazo.com/419b6c454e1434d18b9b8323074d547e

2019-04-07 08:51 UTC, yuki-uchida requested changes

2019-04-07 08:51 UTC, yuki-uchida commented on app/assets/stylesheets/single/_l-single.scss
> +    .l-single-content{
BEMに沿ったクラス命名を行い、アンバサンドを活用した省略系で記述してください

2019-04-07 08:51 UTC, yuki-uchida commented on app/assets/stylesheets/single/_login-panel.scss
> +          margin:24px 0 0;
この辺りもBEMに沿ってください

2019-04-07 08:51 UTC, yuki-uchida commented on app/assets/stylesheets/single/_single-header.scss
> +    display: inline-block;
ここも

2019-04-07 23:09 UTC, hujiyuta commented on app/assets/stylesheets/single/_single-header.scss
> +    display: inline-block;
修正しました

https://gyazo.com/1243d21ffe617927a78cb482affcfd45
https://gyazo.com/5ffcb0343f2e904458e309c2c2ab3324

2019-04-07 23:10 UTC, hujiyuta commented
上記コメントを参考に修正しました

https://gyazo.com/1243d21ffe617927a78cb482affcfd45
https://gyazo.com/5ffcb0343f2e904458e309c2c2ab3324

2019-04-08 02:03 UTC, miyagit commented on config/routes.rb
> +  #   collection do
collectionではなくてresourcesを使いましょう。コントローラーの方もそうなってたと思うので修正お願いします。

2019-04-08 13:45 UTC, hujiyuta commented on config/routes.rb
> +  #   collection do
resourcesにルーティングを変更しました。この変更に伴いsamples_controllerも７つのアクション内、HTTPメソッドがGETになるアクションで各view（新規登録画面、ログイン画面）を読み込むようにしました。

2019-04-09 02:09 UTC, shingoteshima commented
LGTM

2019-04-09 03:50 UTC, KatsuhiroSaito commented on app/views/shared/_single-footer.html.haml
> +    = link_to image_tag("logo-gray.svg", alt: "mercari", height:"65", width:"80",class: '.single-footer-logo__image')
シンボルを用いてclass名を書く場合は、class名の頭にピリオドは不要な気がするのですが、どうでしょうか？
つまり、class: 'single-footer-logo__image'でいい気がします。

検証ツールを使って、この要素の部分のclass名がどうなっているか確認していただけますか？

2019-04-09 04:05 UTC, KatsuhiroSaito commented on app/assets/stylesheets/single/_single-btn.scss
> +  background: $white url("google_logo.jpeg") no-repeat;
こないだslackでお話したとおり、image-urlを使わないと、assets/imagesに保存した画像は本番環境できちんと表示されない気がします。

参考：Qiita「Railsでproduction環境だけ背景画像が読み込まれない」(https://qiita.com/ebkn/items/249fa1caa704f69809ad)

2019-04-09 04:16 UTC, KatsuhiroSaito commented on app/views/shared/_single-footer.html.haml
> +  %ul.sigle-footer-nav.clrearfix
clearfixはclass名に'clearfix'を与えただけでは適用されません。
今回は"_clearfix.scss"にあるmixinをincludeして適用して欲しいです。
なので、
・'clearfix'というクラス名は削除してください。
・'_single-footer.scss'で'_clearfix.scss'をimportする。
・single-footer-navのCSSで、'@include clearfix();'を記述する。

2019-04-09 04:59 UTC, KatsuhiroSaito commented on app/views/shared/_single-footer.html.haml
> +%footer.sigle-footer
BEMの命名規則に則れば、"single-footer", "single-footer-nav", "single-footer-logo"はBlockになりますが、その認識でよろしいでしょうか？

僕の場合、以下のQiita記事を参考に「SCSSファイルは1blockにつき1ファイルで作成」しているのですが、どうしましょうか？藤原さんの場合は、_single-footer.scssに全てのCSSを記述されていますよね。

BlockごとにSCSSファイルをファイルを分けるか、もしくは"single-footer__logo", "single-footer__copyright"のようにロゴの部分、コピーライトの部分を"single-footer"というBlockのElementとみなすのはいかがでしょうか？

その場合は、公式ドキュメントでは、"single-footer__logo__image"のようにElementのElementを作ることは推奨されていないので、例えば"single-footer-logo__image"は"single-footer__logo-image"になりますかね。

https://en.bem.info/methodology/quick-start/#element

2019-04-09 14:00 UTC, hujiyuta commented on app/views/shared/_single-footer.html.haml
> +    = link_to image_tag("logo-gray.svg", alt: "mercari", height:"65", width:"80",class: '.single-footer-logo__image')
コピペした時にピリオドが残ってたので削除した！

2019-04-09 14:13 UTC, hujiyuta commented on app/assets/stylesheets/single/_single-btn.scss
> +  background: $white url("google_logo.jpeg") no-repeat;
修正しました

2019-04-09 22:25 UTC, hujiyuta commented on app/views/shared/_single-footer.html.haml
> +  %ul.sigle-footer-nav.clrearfix
clreafixをincludeで適用しました！
実際のサイト画面を確認したのですが、そもそもfloatさせている要素がないのでなぜ適用してるのか疑問が残りました(^_^;)

2019-04-09 23:02 UTC, hujiyuta commented on app/views/shared/_single-footer.html.haml
> +%footer.sigle-footer
sigle-footer-XXXでblock名定義しているので、他のスタイル設定でblock名が重複する可能性が低く、ファイルを分割するよりも管理しやすいと思うので一旦このままでお願いします！

2019-04-10 12:38 UTC, KatsuhiroSaito commented on app/views/samples/login.html.haml
> +        %button#facebook-login.btn-default.btn-sns.btn-sns-facebook
BEMのルールではidセレクタは使うべきでないとされています。ここでidセレクタを使っているのは何か理由はありますか？

参考：https://github.com/juno/bem-methodology-ja/blob/master/definitions.md
（「ブロックの反復」のところに「IDベースのCSSクラスを使ってはならない」「『一意なものにはしない』という我々の要求を満たすため、クラスセレクタのみを使う。」と書いてあります。）

2019-04-10 13:30 UTC, KatsuhiroSaito commented on app/views/samples/signup.html.haml
> +          %button#facebook-login.btn-default.btn-sns.btn-sns-facebook
login.html.hamlの11行目にも、ここにも"facebook-login"というidが登場してますよね。。。本家メルカリでもそうなっているというのは十分承知なのですが、本来idセレクタは繰り返し用いらないはずなのに、同じidが複数回登場して大丈夫なのでしょうか？

もしかしたらgoogleやfacebookアカウントを使ってログイン・サインアップさせるgemか何かの仕様なのかもしれませんが、ここら辺は今後、慎重に様子を見る必要がありそうですね。

2019-04-10 13:50 UTC, KatsuhiroSaito commented on app/assets/stylesheets/single/_single-btn.scss
> +.btn-default{
これらのクラス名が本家メルカリで使われているのは十分承知ですが、これらはBEMの方法論に基づいて作られたものではないと思います。おそらくOOCSSというCSS設計で本家メルカリは作られています（たぶん）。

違う方法論で作られた本家メルカリのクラス名をBEMに沿ってクラス名を命名している私たちのプロジェクトにそのまま用いると、複数のCSS設計が混在し、カオスになると思うのでBEMに統一すべきだと思うのですが、藤原さんはどのようにお考えでしょうか？少なくとも私は、トップページのマークアップでは複数のクラス名を与えてスタイルを作るということはせず、全てBEMの方法論でマークアップしています。

https://qiita.com/nezurika/items/a964e21d3596b0ee4c9a

2019-04-10 14:14 UTC, hujiyuta commented on app/assets/stylesheets/single/_single-btn.scss
> +.btn-default{
ボタンのid設定は、スタイル設定ではなくおそらくjavascript等で機能実装・処理する為にボタンにid設定していると思われます。

基本的に私はメルカリの本番サイトを参考にしています。（全ての構造を理解できていないですが。）。本番サイトではご指摘いただいたボタンのスタイルについて、複数のクラスを適用しているのは何らかの意図があると思います。

今後進め始め方ですが、時間の制限もあるので自分としては個別の箇所で完全な水準を目指すのではなく、一定の機能を確保できて、致命傷にならなければ実装を進めいければと思います。
色々ご意見あると思うのでメッセージでのやりとりでなく、今週末のmtgで相談できればと思います。

2019-04-10 14:45 UTC, KatsuhiroSaito commented on app/assets/stylesheets/single/_single-btn.scss
> +.btn-default{
「複数のクラスを適用しているのは何らかの意図がある」というのは十分承知しています。
ただ上記でお伝えした通り、本家メルカリと私たちのメルカリは違うCSS設計・思想で成り立っています。なので、「本家メルカリのCSSがこうだから」という理由でそのまま同じことを私たちのメルカリですることはできない/相応しくないと個人的には思っています。

今週末のmtgでこの件については話し合いさせてください。

2019-04-12 11:10 UTC, KatsuhiroSaito commented on app/views/shared/_single-footer.html.haml
> +%footer.sigle-footer
お疲れ様です！
ここは"single-footer"の打ち間違いではないでしょうか？？（iとgの間にnが抜けている）
"sigle-footer-nav"も同様です。ご確認よろしくお願いいたします！

2019-04-12 11:11 UTC, KatsuhiroSaito commented on app/views/shared/_single-footer.html.haml
> +%footer.sigle-footer
s

2019-04-12 11:20 UTC, KatsuhiroSaito commented on app/assets/stylesheets/single/_single-footer.scss
> +.sigle-footer{
お疲れ様です！
ここは"single-footer"の打ち間違いではないでしょうか？？（iとgの間にnが抜けている）
"sigle-footer-nav"も同様です。ご確認よろしくお願いいたします！

2019-04-14 22:43 UTC, hujiyuta commented
新規登録画面
https://gyazo.com/7b821b483c0537ff75b952d017089eb1
https://gyazo.com/d6d06cbb73b67f63fe88be36a36c20dc

ログイン画面
https://gyazo.com/8f96307a0c268dddd40967cbd2a58de9

2019-04-15 02:07 UTC, TOMARUMARU approved these changes
LGTM

2019-04-15 05:48 UTC, merged